config/routes.rb
Rails.application.routes.draw do
  resources :jobtitles
  resources :magazines
  resources :oenologists
  devise_for :users
  resources :wine_strains
  resources :strains
  resources :wines

  root 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :strains, through: :wine_strains, dependent: :destroy
    has_many :wine_oenologists, dependent: :destroy
    has_many :oenologists, through: :wine_oenologists, dependent: :destroy


    def addStrainPercent(percents)
        percents.each do |strain_id, percentage|
            if percentage != ''
                temp_strain = wine_strains.where(strain_id: strain_id).first
                temp_strain.percentage = percentage
                temp_strain.save
            end
        end 
    end

    def strainnames_and_percentages
        list = []
        newe = []
        wine_strains.map do |ws|
            list << [ws.strain.name, ws.percentage ]
            # "#{ws.strain.name} (#{ws.percentage}%)"
        end
        list.sort_by{ |strain| strain[0] }.each do |wso|
            newe << "#{wso[0]}  (#{wso[1]}%)"
        end
        newe.join(', ')
    end 

    def oenologist_name
        oenologists.map do |wine_oenologist|
            wine_oenologist.name
        end.join(', ')
    end   

    def to_s
        name
    end

    

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :authorize_admin!, except: [:index]

  # GET /wines or /wines.json
  def index
    @wines = Wine.order('name DESC')
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @oenologist = Wine.order(:age)
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        @wine.addStrainPercent(params[:wine][:percentage])
        # @wine.addOenologist(params[:wine][:oenologists])
        # @wine.oenologists.create(id: params[:wine][:oenologists])
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :score, {strain_ids: [] }, :percentage, {oenologist_ids: []})
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :oenologists %>
    <%= form.collection_check_boxes(:oenologist_ids, Oenologist.all.order(:age), :id, :name) do |oe| %>
      <% oe.label  class: "label-checkbox" do %>
      <%= oe.check_box + oe.text%>
      <% end %>
    <% end %>
  </div>


    <div class="field">
    <%= form.label :strains %>
    <%= form.collection_check_boxes(:strain_ids, Strain.where(available:true), :id, :name) do |strain| %>
      <% strain.label  class: "label-checkbox" do %>
      <%= strain.check_box + strain.text%>

      
      <%= form.label :percentage %>
      <%= text_field("wine[percentage]", strain.value) %>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Score</th>
      <th>Strain</th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.oenologist_name %></td>
        <td><%= wine.score %></td>
        <td><%= wine.strainnames_and_percentages %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Show', wine %></td>
          <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
          <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>

<% if current_user.admin?  %>
  <%= link_to 'New Wine', new_wine_path %>
  <%= link_to 'New Strain', new_strain_path %>
  <%= link_to 'Oenologist', oenologists_path %>
  <%= link_to 'Magazines', magazines_path %>
  <%= link_to 'Jobtitles', jobtitles_path %>
  
<% end %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @wine.score %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>